###############################################################################
#
# Game Makefile template
#
###############################################################################

MAIN=leveledit.d

#------------------------------------------------------------------------------

EXE=

LDFLAGS=
LIBDIRS=
LIBS=
OBJS=

BLOBFILES=data/

#------------------------------------------------------------------------------

BLOBFILES += engine/stock/unsorted

#------------------------------------------------------------------------------
# Add items you use to BLOB.
#------------------------------------------------------------------------------

BLOBFILES += engine/render/scene3d/glsl/
BLOBFILES += engine/render/postprocess/glsl/
BLOBFILES += engine/stock/system

include engine/build/Makegame.mak

