env = Environment()

#env["DFLAGS"] = "-unittest"
#env["MAIN"] = "../../engine/util/lua.d"
env["MAIN"] = "luademo.d"
env["BLOBFILES"] = []

env.SConscript("../../engine/build/scons/build.py", "env")

