###############################################################################
#
#
#
###############################################################################

EXE=sketch

MAIN=sketch.d

BLOBFILES=data/

#------------------------------------------------------------------------------

LIBDIRS=
LIBS=
LDFLAGS=

#------------------------------------------------------------------------------

BLOBFILES += engine/stock/
BLOBFILES += engine/render/shaders/glsl/
# BLOBFILES += ../pacman/data/images/ChomperSprites.png

include engine/build/Makegame.mak

