###############################################################################
#
#
#
###############################################################################

MAIN=wolfish.d

BLOBFILES=data/

#------------------------------------------------------------------------------

EXE=

#------------------------------------------------------------------------------

LIBDIRS=
LIBS=
LDFLAGS=

#------------------------------------------------------------------------------

BLOBFILES += engine/render/scene3d/glsl/
BLOBFILES += engine/render/postprocess/glsl/

BLOBFILES += engine/stock/
# BLOBFILES += /usr/share/fonts/truetype/freefont/

include engine/build/Makegame.mak

