###############################################################################
#
#
#
###############################################################################

EXE=pacman
ENGINE = ../../engine/

MAIN=pacman.d

BLOBFILES=data/

#------------------------------------------------------------------------------

LIBDIRS=
LIBS=
LDFLAGS=

#------------------------------------------------------------------------------

#BLOBFILES += $(ENGINE)/stock/fonts/Courier\ Prime/
BLOBFILES += $(ENGINE)/stock
BLOBFILES += $(ENGINE)/render/shaders/glsl/

include $(ENGINE)/build/Makegame.mak

