###############################################################################
#
#
#
###############################################################################

EXE=pacman

MAIN=pacman.d

BLOBFILES=data/

#------------------------------------------------------------------------------

LIBDIRS=
LIBS=
LDFLAGS=

#------------------------------------------------------------------------------

#BLOBFILES += engine/stock/fonts/Courier\ Prime/
BLOBFILES += engine/stock
BLOBFILES += engine/render/shaders/glsl/

include engine/build/Makegame.mak

