###############################################################################
#
#
#
###############################################################################

EXE=cylinderium

MAIN=cylinderium.d

BLOBFILES=data/

#------------------------------------------------------------------------------

LIBDIRS=
LIBS=
LDFLAGS=

#------------------------------------------------------------------------------

BLOBFILES += engine/render/scene3d/glsl/
BLOBFILES += engine/render/postprocess/glsl/
BLOBFILES += engine/stock/

include engine/build/Makegame.mak

