#------------------------------------------------------------------------------

import sys, os

env = Environment(ENV = {"PATH": os.environ["PATH"]})
env["ENGINE"] = "../../engine/"

sys.path.append(env.Dir("$ENGINE/build/").abspath)
from SconsEnv import *
SetEnv(env)

#------------------------------------------------------------------------------

BLOB_Files = findfiles(
    env.Dir("$ENGINE/render/scene3d/glsl/").abspath,
    env.Dir("$ENGINE/render/postprocess/glsl/").abspath,
    env.Dir("$ENGINE/stock/system/").abspath,
)

#------------------------------------------------------------------------------

env.BLOB("bin/BLOB.zip", BLOB_Files, ARCHIVEROOT = "$ENGINE/../")

env.Command("bin/empty", "empty.d", "rdmd -debug --build-only $DFLAGS -of$TARGET $SOURCES")
#env.Program("empty.d")
